<?php

declare(strict_types=1);

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@picocss/pico' => [
        'version' => '1.5.10',
    ],
    '@picocss/pico/css/pico.min.css' => [
        'version' => '1.5.10',
        'type' => 'css',
    ],
    'htmx.org' => [
        'version' => '1.9.9',
    ],
    '@picocss/pico/css/pico.classless.min.css' => [
        'version' => '1.5.10',
        'type' => 'css',
    ],
];
